language: node_js
node_js:
- "stable"
cache:
  yarn: true
  directories:
  - node_modules
install:
- npm install -g firebase-tools
script:
- node_modules/gulp/bin/gulp.js build
after_success:
- 'if [ "${TRAVIS_BRANCH}" = "production" ]; then firebase deploy --non-interactive --token "$FIREBASE_TOKEN" --project ampstart-8dc54; fi'
- 'if [ "${TRAVIS_BRANCH}" = "master" ]; then firebase deploy --non-interactive --token "$FIREBASE_TOKEN" --project ampstart-staging; fi'
branches:
  only:
  - production
  - master
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
